<?php $pageTitle='A little closer to the Himalayas'; $activeNav='home'; require __DIR__.'/partials/header.php'; ?>
<main id="main">
<section class="home-hero"><img src="/Assets/images/bg.jpg" alt="A peaceful pool overlooking green hills and Himalayan peaks" fetchpriority="high"><div class="shell hero-content"><p class="eyebrow">Pokhara, Nepal · A different pace</p><h1>Somewhere to stay.<br><em>Something to feel.</em></h1><p>Mountain mornings. Unhurried moments. Find your own little corner of Nepal, and make yourself at home.</p><a class="button button-light" href="/rooms">Explore our rooms <?= ns_icon('arrow') ?></a></div><div class="hero-bottom"><?= ns_icon('pin') ?> At home in the Himalayas</div></section>
<div class="shell search-wrap"><?php require __DIR__.'/partials/search-form.php'; ?></div>
<div class="shell intro-strip"><p><?= ns_icon('mountain') ?> A Himalayan setting</p><p><?= ns_icon('bed') ?> Space to settle in</p><p><?= ns_icon('leaf') ?> A slower kind of escape</p></div>
<section class="shell section"><div class="section-heading"><div><p class="eyebrow">The stay collection</p><h2>Your room.<br>Your kind of retreat.</h2></div><a class="text-link" href="/rooms">Discover all rooms <?= ns_icon('arrow') ?></a></div><div class="rooms-grid home-rooms"><?php foreach (array_slice($rooms ?? [],0,3) as $room) require __DIR__.'/partials/room-card.php'; ?></div><?php if(empty($rooms)): ?><div class="empty-state"><h3>Good things take a moment.</h3><p>Our room collection is being updated. Please check back shortly.</p></div><?php endif; ?></section>
<section class="story-section section"><div class="shell story-grid"><div class="story-photo"><img src="/Assets/images/MountainView.webp" alt="A restful room at NepalStay" loading="lazy"><div class="image-caption"><small>Less rush. More room.</small>Stay a little longer.</div></div><div class="story-copy"><p class="eyebrow">Welcome to NepalStay</p><h2>A place to pause.<br>A place to belong.</h2><p>Every good journey needs a place to return to. Somewhere to put down your bags, open the curtains, and let the day unfold. That is the feeling behind NepalStay.</p><a class="text-link" href="/about">Our story <?= ns_icon('arrow') ?></a></div></div></section>
<section class="shell section"><div class="section-heading"><div><p class="eyebrow">Make it your own</p><h2>A little more than a room.</h2></div><p>From your first look to your next visit, a simpler way to plan your time away.</p></div><div class="feature-grid"><div class="feature"><?= ns_icon('bed') ?><h3>Find your fit</h3><p>Compare rooms, guest capacity, and nightly prices in one place.</p></div><div class="feature"><?= ns_icon('calendar') ?><h3>Choose your dates</h3><p>Check availability for the dates and people that matter to you.</p></div><div class="feature"><?= ns_icon('user') ?><h3>Keep it together</h3><p>Book while signed in to keep your reservation history in your account.</p></div></div></section>
<section class="shell section" style="padding-top:0"><div class="destination-banner"><div><p class="eyebrow">Your next chapter</p><h2>The mountains are calling.<br>Make a little room.</h2><p>Explore the rooms and find the dates that work for you.</p></div><a class="button button-light" href="/booking">Plan your stay <?= ns_icon('arrow') ?></a></div></section>
</main><?php require __DIR__.'/partials/footer.php'; ?>